### PR TITLE
task states

### PR DESCRIPTION
**Pull request by eparejatobes**
I want to add a notion of states for tasks, reflecting the standard intuition about them; they could be planned, started, finished, etc.
- [Wikipedia - Task management](https://en.wikipedia.org/wiki/Task_management#Task_life_cycle)

### CODE REVIEW

**Comment by eparejatobes** [comment]
@laughedelic my initial idea about this is: make `AnyTask ≤ AnyType` and identify states with denotations thereof. From there we can make `AnyProject` a `AnyRecord` of `AnyTask`s. WDYT?

**Comment by laughedelic** [comment]
:+1:

**Comment by eparejatobes** [comment]
I think it good enough for a first cut. @laughedelic ?

**Comment by laughedelic** [comment]
yep! :+1: :shipit:

**Pull request merged**
